### ISSUE TITLE
[COMPONENT] Add Azure Function App component

### ISSUE THREAD

**Issue by Damianjsp** [Damianjsp/one-platform#11]
## Azure Service Information
- **Service Name**: Azure Function App
- **Azure Provider Resource**: azurerm_linux_function_app, azurerm_windows_function_app, azurerm_function_app_slot
- **Service Documentation**: https://docs.microsoft.com/en-us/azure/azure-functions/
- **Terraform Provider Docs**: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app

## Component Requirements
- [x] **Resource Creation**: Basic resource creation functionality
- [x] **Configuration Options**: Support for common configuration scenarios
- [x] **Dependencies**: Integration with existing components (RG, VNet, Subnet)
- [x] **Private Endpoints**: Support for private endpoint connectivity
- [x] **Naming Convention**: Follow established naming patterns
- [x] **Tagging**: Consistent resource tagging

## Use Cases
Describe the primary use cases for this component:

1. **Development Environment**:
   - Consumption plan for cost optimization
   - Basic monitoring and logging
   - Development-friendly configuration

2. **Production Environment**:
   - Premium or Dedicated plan for performance
   - VNet integration for security
   - Application Insights integration
   - Key Vault integration for secrets

3. **Security Requirements**:
   - Private endpoint connectivity
   - Managed identity integration
   - VNet integration for network isolation

## Configuration Example
Provide an example of how this component would be configured:

```yaml
components:
  terraform:
    azure-function-app:
      vars:
        name: "api"
        os_type: "linux"
        runtime_version: "~4"
        
        # Service plan configuration
        service_plan_id: "${components.terraform.azure-service-plan.outputs.service_plan_id}"
        
        # Application settings
        app_settings:
          FUNCTIONS_WORKER_RUNTIME: "python"
          PYTHON_VERSION: "3.11"
          
        # Storage account integration
        storage_account_name: "${components.terraform.azure-storage-account.outputs.storage_account_name}"
        storage_account_access_key: "${components.terraform.azure-storage-account.outputs.primary_access_key}"
        
        # VNet integration
        virtual_network_subnet_id: "${components.terraform.azure-subnet.outputs.subnet_id}"
        
    # Example with private endpoint
    azure-private-endpoint-function:
      metadata:
        component: azure-private-endpoint
      vars:
        name: "function"
        private_connection_resource_id: "${components.terraform.azure-function-app.outputs.function_app_id}"
        subresource_names: ["sites"]
```

## Dependencies
This component will depend on:
- [x] azure-resource-group
- [x] azure-vnet (for VNet integration)
- [x] azure-subnet (for VNet integration and private endpoints)
- [x] azure-storage-account (for function storage)
- [x] azure-service-plan (for hosting plan)
- [x] Other: azure-application-insights (for monitoring)

## Private Endpoint Support
- [x] **Required**: This service needs private endpoint support
- [ ] **Optional**: Private endpoints would be beneficial
- [ ] **Not Applicable**: Service doesn't support private endpoints

If private endpoints are supported:
- **Subresource Names**: sites
- **Private DNS Zone**: privatelink.azurewebsites.net

## Implementation Checklist
- [ ] Terraform module created
- [ ] Variables defined with descriptions
- [ ] Outputs provided for dependent components
- [ ] Catalog defaults created
- [ ] Environment mixins created (dev/prod)
- [ ] Stack integration example provided
- [ ] Component README with usage examples
- [ ] Validation tests passing
- [ ] Private endpoint compatibility verified

## Additional Context
Add any other context, requirements, or considerations for this component:

- **Runtime Support**: PowerShell, Python, Node.js, .NET, Java
- **Hosting Options**: Consumption, Premium, and App Service Plan
- **Security Features**: Managed identity, Key Vault integration
- **Performance Requirements**: Premium plan for VNet integration
- **Cost Considerations**: Consumption plan for development environments

## References
- [Azure Functions Documentation](https://docs.microsoft.com/en-us/azure/azure-functions/)
- [Terraform AzureRM Function App Resources](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app)
- [Azure Functions VNet Integration](https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options)
